# Generated by Django 3.2.15 on 2022-10-03 17:14

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Фамилия')),
                ('address', models.TextField(db_index=True, max_length=200, verbose_name='Адрес заказчика')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Номер телефона')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='foodcartapp.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
