# Generated by Django 3.2.15 on 2022-10-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_orderproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('handled', 'Обработанный'), ('unhandled', 'Необработанный'), ('in_work', 'В работе')], db_index=True, default='in_work', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
