# Generated by Django 3.2.15 on 2022-10-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('handled', 'Обработанный'), ('unhandled', 'Необработанный'), ('in_work', 'В работе')], db_index=True, default='unhandled', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
