# Generated by Django 3.2.15 on 2022-10-16 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20221016_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDistanceToRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_coordinates', models.FloatField(verbose_name='Координаты заказчика')),
                ('distance', models.FloatField(verbose_name='Расстояние в км')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_distances', to='foodcartapp.order', verbose_name='заказ')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_distances', to='foodcartapp.product', verbose_name='ресторан')),
            ],
        ),
    ]
